### ISSUE TITLE
Milestone: version 0.1.0

### ISSUE THREAD

**Issue by mbillingr** [mbillingr/forester#9]
Version 0.1.0 marks the end of the experimental development period. It will focus on functionality rather than usability.

Non-goals:
- Ease of use
  - Don't provide impls of Data traits for builtin types. This is difficult because of conflicts.(i.e. a regressor and a classifier may both want to implement `SampleDescription` for `[X]`, but they can't because they require different SampleDescriptions.) This prevents usage like `model.predict([5])`. Instead this would need to be written as something like `model.predict(Sample::new([5], ()))`.

To-Dos:

- [x] README
- [ ] Basic documentation
- [x] Structure: how to organize modules, traits, structs, ...
- [ ] Usable high-level API (simple but flexible)
  - [x] ExtraTreesRegressor
  - [x] ExtraTreesClassifier
  - [ ] RandomForest
    - [x] Bootstrapping: #25 
    - [x] CART: #27 
    - [ ] Regressor
    - [ ] Classifier
- [ ] More low-level components
  - [ ] Probabilistic leaf predictors
    - [ ] ConstGaussian
    - [ ] LinearRegression
  - [ ] Prototype Probabilistic/Soft Tree components
